<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Osoba [
  <!ELEMENT Osoba (PunoIme,DatumRodjenja,Adresa,Email+)>
  <!ELEMENT PunoIme (Ime, SrednjeIme?, Prezime+)>
  <!ELEMENT DatumRodjenja (Dan, Mesec, Godina)>
  <!ELEMENT Adresa (#PCDATA)>
  <!ELEMENT Email (#PCDATA)>
  <!ELEMENT Ime (#PCDATA)>
  <!ELEMENT SrednjeIme (#PCDATA)>
  <!ELEMENT Prezime (#PCDATA)>
  <!ELEMENT Dan (#PCDATA)>
  <!ELEMENT Mesec (#PCDATA)>
  <!ELEMENT Godina (#PCDATA)>
  <!ATTLIST Adresa tip (Privremena | Stalna) "Privremena">
  <!ATTLIST Email tip (Sluzbeni | Privatni) #IMPLIED>
]>
<Osoba>
  <PunoIme>
    <Ime>Anja</Ime>
    <SrednjeIme></SrednjeIme>
    <Prezime>Mladenovic</Prezime>
  </PunoIme>
  <DatumRodjenja>
    <Dan>22</Dan>
    <Mesec>2</Mesec>
    <Godina>1999</Godina>
  </DatumRodjenja>
  <Adresa tip="Stalna">Beograd</Adresa>
  <Email tip="Privatni">mladenovicanjaa@gmail.com</Email>
</Osoba>
